name: Continuous Integration Master

on:
  push:
    branches:
      - main
jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Set Version
        id: version
        run: |
          echo "::set-output name=PKG_VERSION::$(pip show WAPB | grep Version | sed 's/Version://g' | sed 's/ //g')"
      - name: Crete Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.PKG_VERSION }}
          draft: false
          prerelease: false